// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:catchline/data/models/audio_clip_meta.dart';
import 'package:catchline/data/models/item.dart';
import 'package:catchline/data/models/item_kind.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AudioClipMetaAdapter());
    registerAdapter(ItemAdapter());
    registerAdapter(ItemKindAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AudioClipMetaAdapter());
    registerAdapter(ItemAdapter());
    registerAdapter(ItemKindAdapter());
  }
}
